spring:
  data:
    mongodb:
      uri: mongodb://admin:0@localhost:27017/joboffers-web

scheduling:
  enabled: true

joboffers:
  scheduler:
    request:
      delay: PT3H
  offer-fetcher:
    http:
      client:
        config:
          connectionTimeout: 10000
          readTimeout: 10000
          port: 5057
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com

