spring:
  data:
    mongodb:
      uri: mongodb://admin:0@localhost:27017/joboffers-web

joboffers:
  offer-fetcher:
    http:
      client:
        config:
          connectionTimeout: 1000
          readTimeout: 1000
          port: 5057
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com:5057/offers
