

spring:
  data:
    mongodb:
      uri: mongodb://admin:0@localhost:27017/joboffers-web
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

scheduling:
  enabled: true

joboffers:
  scheduler:
    request:
      delay: PT3H
  offer-fetcher:
    http:
      client:
        config:
          connectionTimeout: 10000
          readTimeout: 10000
          port: 5057
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com

auth:
  jwt:
    expiration-days: 30
    secret: e8c3f1a728d49a75b3c428fbbf32a5e2f342b6d90e729178a134c6e5e8cafe9f5b3d3a8fc3e2494a6bde072c18f4b7d9e3a28bc7a91e42f5d71c38e5d9e3b2a4
    issuer: job-offers-backend
